In [1]:
import pandas as pd
import os
from IPython.display import display
from pathlib import Path

In [2]:
#file_path = Path("/Users/raulbazan/Desktop/HistoricalData/DixonMeadowPreserve/2025/April2025.csv")
pd.set_option('display.max_columns', 1000)
df = pd.read_csv("/Users/raulbazan/Desktop/HistoricalData/DixonMeadowPreserve/2025/April2025.csv")

In [3]:
df['birdCount'] = df['howMany'].astype('Int64')

In [4]:
df = df.drop(['obsValid', 'obsReviewed', 'locationPrivate', 'exoticCategory', 'subId', 'howMany'], axis=1)

In [5]:
df.dtypes

speciesCode     object
comName         object
sciName         object
locId           object
locName         object
obsDt           object
lat            float64
lng            float64
birdCount        Int64
dtype: object

In [6]:
df['obsDt'] = pd.to_datetime(df['obsDt'], format='%Y-%m-%d %H:%M:%S')

In [7]:
pd.set_option('display.max_columns', None)
display(df)

,speciesCode,comName,sciName,locId,locName,obsDt,lat,lng,birdCount
0,cangoo,Canada Goose,Branta canadensis,L3041917,Dixon Meadow Preserve,2025-04-01 18:20:00,40.100315,-75.240212,2
1,moudov,Mourning Dove,Zenaida macroura,L3041917,Dixon Meadow Preserve,2025-04-01 18:20:00,40.100315,-75.240212,1
2,turvul,Turkey Vulture,Cathartes aura,L3041917,Dixon Meadow Preserve,2025-04-01 18:20:00,40.100315,-75.240212,4
3,rethaw,Red-tailed Hawk,Buteo jamaicensis,L3041917,Dixon Meadow Preserve,2025-04-01 18:20:00,40.100315,-75.240212,1
4,normoc,Northern Mockingbird,Mimus polyglottos,L3041917,Dixon Meadow Preserve,2025-04-01 18:20:00,40.100315,-75.240212,3
...,...,...,...,...,...,...,...,...,...
644,turvul,Turkey Vulture,Cathartes aura,L3041917,Dixon Meadow Preserve,2025-04-30 08:33:00,40.100315,-75.240212,2
645,amekes,American Kestrel,Falco sparverius,L3041917,Dixon Meadow Preserve,2025-04-30 08:33:00,40.100315,-75.240212,1
646,amecro,American Crow,Corvus brachyrhynchos,L3041917,Dixon Meadow Preserve,2025-04-30 08:33:00,40.100315,-75.240212,1
647,eursta,European Starling,Sturnus vulgaris,L3041917,Dixon Meadow Preserve,2025-04-30 08:33:00,40.100315,-75.240212,10
648,comgra,Common Grackle,Quiscalus quiscula,L3041917,Dixon Meadow Preserve,2025-04-30 08:33:00,40.100315,-75.240212,1

In [8]:
#path = '/Users/raulbazan/Desktop/CleanData/DixonMeadowPreserve/2025/April2025.csv'
#filepath = Path(path)

In [9]:
#df.to_csv(filepath, index=False)

In [10]:
print(df[df['birdCount'].isnull()])

    speciesCode               comName                    sciName     locId  \
10       rewbla  Red-winged Blackbird        Agelaius phoeniceus  L3041917
61       dowwoo      Downy Woodpecker        Dryobates pubescens  L3041917
62       bnhcow  Brown-headed Cowbird             Molothrus ater  L3041917
263      eursta     European Starling           Sturnus vulgaris  L3041917
265      amerob        American Robin         Turdus migratorius  L3041917
266      houfin           House Finch       Haemorhous mexicanus  L3041917
268      rewbla  Red-winged Blackbird        Agelaius phoeniceus  L3041917
382      eursta     European Starling           Sturnus vulgaris  L3041917
384      amerob        American Robin         Turdus migratorius  L3041917
387      rewbla  Red-winged Blackbird        Agelaius phoeniceus  L3041917
397      treswa          Tree Swallow        Tachycineta bicolor  L3041917
398      normoc  Northern Mockingbird          Mimus polyglottos  L3041917
399      amerob        American Robin         Turdus migratorius  L3041917
400      amegfi    American Goldfinch             Spinus tristis  L3041917
401      savspa      Savannah Sparrow  Passerculus sandwichensis  L3041917
402      sonspa          Song Sparrow          Melospiza melodia  L3041917
403      rewbla  Red-winged Blackbird        Agelaius phoeniceus  L3041917
573      amerob        American Robin         Turdus migratorius  L3041917
576      sonspa          Song Sparrow          Melospiza melodia  L3041917
577      rewbla  Red-winged Blackbird        Agelaius phoeniceus  L3041917

                   locName               obsDt        lat        lng  \
10   Dixon Meadow Preserve 2025-04-01 18:20:00  40.100315 -75.240212
61   Dixon Meadow Preserve                 NaT  40.100315 -75.240212
62   Dixon Meadow Preserve                 NaT  40.100315 -75.240212
263  Dixon Meadow Preserve 2025-04-13 16:32:00  40.100315 -75.240212
265  Dixon Meadow Preserve 2025-04-13 16:32:00  40.100315 -75.240212
266  Dixon Meadow Preserve 2025-04-13 16:32:00  40.100315 -75.240212
268  Dixon Meadow Preserve 2025-04-13 16:32:00  40.100315 -75.240212
382  Dixon Meadow Preserve 2025-04-19 17:56:00  40.100315 -75.240212
384  Dixon Meadow Preserve 2025-04-19 17:56:00  40.100315 -75.240212
387  Dixon Meadow Preserve 2025-04-19 17:56:00  40.100315 -75.240212
397  Dixon Meadow Preserve 2025-04-20 17:15:00  40.100315 -75.240212
398  Dixon Meadow Preserve 2025-04-20 17:15:00  40.100315 -75.240212
399  Dixon Meadow Preserve 2025-04-20 17:15:00  40.100315 -75.240212
400  Dixon Meadow Preserve 2025-04-20 17:15:00  40.100315 -75.240212
401  Dixon Meadow Preserve 2025-04-20 17:15:00  40.100315 -75.240212
402  Dixon Meadow Preserve 2025-04-20 17:15:00  40.100315 -75.240212
403  Dixon Meadow Preserve 2025-04-20 17:15:00  40.100315 -75.240212
573  Dixon Meadow Preserve 2025-04-28 19:36:00  40.100315 -75.240212
576  Dixon Meadow Preserve 2025-04-28 19:36:00  40.100315 -75.240212
577  Dixon Meadow Preserve 2025-04-28 19:36:00  40.100315 -75.240212

     birdCount
10        <NA>
61        <NA>
62        <NA>
263       <NA>
265       <NA>
266       <NA>
268       <NA>
382       <NA>
384       <NA>
387       <NA>
397       <NA>
398       <NA>
399       <NA>
400       <NA>
401       <NA>
402       <NA>
403       <NA>
573       <NA>
576       <NA>
577       <NA>

In [11]:
df = df.dropna(axis=0, subset=['birdCount'])

In [12]:
df

,speciesCode,comName,sciName,locId,locName,obsDt,lat,lng,birdCount
0,cangoo,Canada Goose,Branta canadensis,L3041917,Dixon Meadow Preserve,2025-04-01 18:20:00,40.100315,-75.240212,2
1,moudov,Mourning Dove,Zenaida macroura,L3041917,Dixon Meadow Preserve,2025-04-01 18:20:00,40.100315,-75.240212,1
2,turvul,Turkey Vulture,Cathartes aura,L3041917,Dixon Meadow Preserve,2025-04-01 18:20:00,40.100315,-75.240212,4
3,rethaw,Red-tailed Hawk,Buteo jamaicensis,L3041917,Dixon Meadow Preserve,2025-04-01 18:20:00,40.100315,-75.240212,1
4,normoc,Northern Mockingbird,Mimus polyglottos,L3041917,Dixon Meadow Preserve,2025-04-01 18:20:00,40.100315,-75.240212,3
...,...,...,...,...,...,...,...,...,...
644,turvul,Turkey Vulture,Cathartes aura,L3041917,Dixon Meadow Preserve,2025-04-30 08:33:00,40.100315,-75.240212,2
645,amekes,American Kestrel,Falco sparverius,L3041917,Dixon Meadow Preserve,2025-04-30 08:33:00,40.100315,-75.240212,1
646,amecro,American Crow,Corvus brachyrhynchos,L3041917,Dixon Meadow Preserve,2025-04-30 08:33:00,40.100315,-75.240212,1
647,eursta,European Starling,Sturnus vulgaris,L3041917,Dixon Meadow Preserve,2025-04-30 08:33:00,40.100315,-75.240212,10
648,comgra,Common Grackle,Quiscalus quiscula,L3041917,Dixon Meadow Preserve,2025-04-30 08:33:00,40.100315,-75.240212,1

In [14]:
df = df.reset_index(drop=True)

In [15]:
df

,speciesCode,comName,sciName,locId,locName,obsDt,lat,lng,birdCount
0,cangoo,Canada Goose,Branta canadensis,L3041917,Dixon Meadow Preserve,2025-04-01 18:20:00,40.100315,-75.240212,2
1,moudov,Mourning Dove,Zenaida macroura,L3041917,Dixon Meadow Preserve,2025-04-01 18:20:00,40.100315,-75.240212,1
2,turvul,Turkey Vulture,Cathartes aura,L3041917,Dixon Meadow Preserve,2025-04-01 18:20:00,40.100315,-75.240212,4
3,rethaw,Red-tailed Hawk,Buteo jamaicensis,L3041917,Dixon Meadow Preserve,2025-04-01 18:20:00,40.100315,-75.240212,1
4,normoc,Northern Mockingbird,Mimus polyglottos,L3041917,Dixon Meadow Preserve,2025-04-01 18:20:00,40.100315,-75.240212,3
...,...,...,...,...,...,...,...,...,...
624,turvul,Turkey Vulture,Cathartes aura,L3041917,Dixon Meadow Preserve,2025-04-30 08:33:00,40.100315,-75.240212,2
625,amekes,American Kestrel,Falco sparverius,L3041917,Dixon Meadow Preserve,2025-04-30 08:33:00,40.100315,-75.240212,1
626,amecro,American Crow,Corvus brachyrhynchos,L3041917,Dixon Meadow Preserve,2025-04-30 08:33:00,40.100315,-75.240212,1
627,eursta,European Starling,Sturnus vulgaris,L3041917,Dixon Meadow Preserve,2025-04-30 08:33:00,40.100315,-75.240212,10
628,comgra,Common Grackle,Quiscalus quiscula,L3041917,Dixon Meadow Preserve,2025-04-30 08:33:00,40.100315,-75.240212,1